export const USER_AUTHENTICATE_REQUEST = "USER_AUTHENTICATE_REQUEST";
export const USER_AUTHENTICATE_SUCCESS = "USER_AUTHENTICATE_SUCCESS";
export const USER_AUTHENTICATE_FAILURE = "USER_AUTHENTICATE_FAILURE";
export const UPDATE_HEADER_TEXT = "UPDATE_HEADER_TEXT";
export const SHOW_LOADING_ACTION = "SHOW_LOADING_ACTION";

// Impact Tracing constants
export const TRACKING_JOBS_LOADING = "TRACKING_JOBS_LOADING";
export const TRACKING_STAGE_FILTER_UPDATE = "TRACKING_STAGE_FILTER_UPDATE";
export const TRACKING_STAGE_FILTER_RESET = "TRACKING_STAGE_FILTER_RESET";
export const RUN_STAGE_1_JOBS_UPDATE = "RUN_STAGE_1_JOBS_UPDATE";
export const RETRIEVE_HOME_JOBS_INFO = "RETRIEVE_HOME_JOBS_INFO";
export const STAGE_1_ROW_DATA_SELECTED = "STAGE_1_ROW_DATA_SELECTED";


export const SET_LOADING_ACTION = "SET_LOADING_ACTION";
export const SET_LOB_ALL_DATA = "SET_LOB_ALL_DATA";
export const SET_LOB_DATA = "SET_LOB_DATA";
export const SET_LOB_LIST_DATA = "SET_LOB_LIST_DATA";
export const SET_MBUCLASS_DATA = "SET_MBUCLASS_DATA";
export const RESET_LOB_DATA = "RESET_LOB_DATA";
export const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";
export const SET_PRODUCT_LIST_DATA = "SET_PRODUCT_LIST_DATA";
export const RESET_PRODUCT_DATA = "RESET_PRODUCT_DATA";
export const SET_FUNDING_TYPE_DATA = "SET_FUNDING_TYPE_DATA";
export const SET_FUNDING_CLASS_DATA = "SET_FUNDING_CLASS_DATA";
export const RESET_FUNDING_DATA = "RESET_FUNDING_DATA";


